apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mintk
spec:
  nodeSets:
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 2Gi
              cpu: 1
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"