apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: base

spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    max_content_length: 500mb
  secureSettings:
  - secretName: s3-credentials

  version: 8.9.0

  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: ["master", "data", "ingest", "transform"]
      # node.remote_cluster_client: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"

        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3

    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: gp3